//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Imput actions/Controles.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Imput actions/Controles.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Controles: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Controles()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""Controles"",
    ""maps"": [
        {
            ""name"": ""PajarosVSCerdos"",
            ""id"": ""aa2769c2-fdcf-44f9-b3ce-9de8843809ca"",
            ""actions"": [
                {
                    ""name"": ""OnMouseDown"",
                    ""type"": ""Button"",
                    ""id"": ""f8a2ef0b-afff-41cb-94e5-db6d915601c4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Posicion"",
                    ""type"": ""Value"",
                    ""id"": ""12808dfd-3790-42fc-9deb-51e4d16efb11"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f8006995-fca3-44b3-a340-dc4f2d095a46"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnMouseDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0318d627-5cfb-485a-994f-30e6ecdf54b9"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Posicion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PajarosVSCerdos
        m_PajarosVSCerdos = asset.FindActionMap("PajarosVSCerdos", throwIfNotFound: true);
        m_PajarosVSCerdos_OnMouseDown = m_PajarosVSCerdos.FindAction("OnMouseDown", throwIfNotFound: true);
        m_PajarosVSCerdos_Posicion = m_PajarosVSCerdos.FindAction("Posicion", throwIfNotFound: true);
    }

    ~@Controles()
    {
        UnityEngine.Debug.Assert(!m_PajarosVSCerdos.enabled, "This will cause a leak and performance issues, Controles.PajarosVSCerdos.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PajarosVSCerdos
    private readonly InputActionMap m_PajarosVSCerdos;
    private List<IPajarosVSCerdosActions> m_PajarosVSCerdosActionsCallbackInterfaces = new List<IPajarosVSCerdosActions>();
    private readonly InputAction m_PajarosVSCerdos_OnMouseDown;
    private readonly InputAction m_PajarosVSCerdos_Posicion;
    /// <summary>
    /// Provides access to input actions defined in input action map "PajarosVSCerdos".
    /// </summary>
    public struct PajarosVSCerdosActions
    {
        private @Controles m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PajarosVSCerdosActions(@Controles wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PajarosVSCerdos/OnMouseDown".
        /// </summary>
        public InputAction @OnMouseDown => m_Wrapper.m_PajarosVSCerdos_OnMouseDown;
        /// <summary>
        /// Provides access to the underlying input action "PajarosVSCerdos/Posicion".
        /// </summary>
        public InputAction @Posicion => m_Wrapper.m_PajarosVSCerdos_Posicion;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PajarosVSCerdos; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PajarosVSCerdosActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PajarosVSCerdosActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PajarosVSCerdosActions" />
        public void AddCallbacks(IPajarosVSCerdosActions instance)
        {
            if (instance == null || m_Wrapper.m_PajarosVSCerdosActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PajarosVSCerdosActionsCallbackInterfaces.Add(instance);
            @OnMouseDown.started += instance.OnOnMouseDown;
            @OnMouseDown.performed += instance.OnOnMouseDown;
            @OnMouseDown.canceled += instance.OnOnMouseDown;
            @Posicion.started += instance.OnPosicion;
            @Posicion.performed += instance.OnPosicion;
            @Posicion.canceled += instance.OnPosicion;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PajarosVSCerdosActions" />
        private void UnregisterCallbacks(IPajarosVSCerdosActions instance)
        {
            @OnMouseDown.started -= instance.OnOnMouseDown;
            @OnMouseDown.performed -= instance.OnOnMouseDown;
            @OnMouseDown.canceled -= instance.OnOnMouseDown;
            @Posicion.started -= instance.OnPosicion;
            @Posicion.performed -= instance.OnPosicion;
            @Posicion.canceled -= instance.OnPosicion;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PajarosVSCerdosActions.UnregisterCallbacks(IPajarosVSCerdosActions)" />.
        /// </summary>
        /// <seealso cref="PajarosVSCerdosActions.UnregisterCallbacks(IPajarosVSCerdosActions)" />
        public void RemoveCallbacks(IPajarosVSCerdosActions instance)
        {
            if (m_Wrapper.m_PajarosVSCerdosActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PajarosVSCerdosActions.AddCallbacks(IPajarosVSCerdosActions)" />
        /// <seealso cref="PajarosVSCerdosActions.RemoveCallbacks(IPajarosVSCerdosActions)" />
        /// <seealso cref="PajarosVSCerdosActions.UnregisterCallbacks(IPajarosVSCerdosActions)" />
        public void SetCallbacks(IPajarosVSCerdosActions instance)
        {
            foreach (var item in m_Wrapper.m_PajarosVSCerdosActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PajarosVSCerdosActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PajarosVSCerdosActions" /> instance referencing this action map.
    /// </summary>
    public PajarosVSCerdosActions @PajarosVSCerdos => new PajarosVSCerdosActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PajarosVSCerdos" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PajarosVSCerdosActions.AddCallbacks(IPajarosVSCerdosActions)" />
    /// <seealso cref="PajarosVSCerdosActions.RemoveCallbacks(IPajarosVSCerdosActions)" />
    public interface IPajarosVSCerdosActions
    {
        /// <summary>
        /// Method invoked when associated input action "OnMouseDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOnMouseDown(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Posicion" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPosicion(InputAction.CallbackContext context);
    }
}
